.\" Filename:      policy-rc.d.8
.\" Purpose:       man page for policy-rc.d
.\" Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>
.\" Bug-Reports:   see http://grml.org/bugs/
.\" License:       This file is licensed under the GPL v2.
.\"###############################################################################

.\"###############################################################
.TH policy-rc.d 8 "2010-12-23" "policy-rc.d"
.SH "NAME"
policy\-rc.d \- wrapper for invoke-rc.d
.\"#######################################################

.P
This is a wrapper script for invoke-rc.d to avoid automatical
startup of init scripts via invoke-rc.d. To configure it
edit /etc/policy-rc.d.conf.

By default you won't notice any differences to Debian's
default behaviour, except that invoke-rc.d won't be executed
if a chroot has been detected (detection using /proc). If
you want to disable automatical startup of newly installed
packages (done via the invoke-rc.d mechanism) just set
EXITSTATUS to '101' in /etc/policy-rc.d.conf. To restore the
default behaviour set EXITSTATUS back to '0' in
/etc/policy-rc.d.conf.

.SH "BUGS"
Please report any problems you find and report feedback and
suggestions to the grml-team.  See http://grml.org/bugs/ for
further information. Thank you!

.SH "COPYRIGHT"
Copyright \(co 2006-2010 by the grml-team.
.\"###### END OF FILE ##########################################################
.\" vim:tw=60
